name: Upload Python Package

on:
  workflow_dispatch:


jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install build
      - name: Build package
        run: python -m build
      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: image-quantizer
          password: pypi-AgENdGVzdC5weXBpLm9yZwIkNGE0OTI4NWQtZTNhNy00OTFkLWExMWMtZjAzMTA4YTY2OTFlAAIleyJwZXJtaXNzaW9ucyI6ICJ1c2VyIiwgInZlcnNpb24iOiAxfQAABiDaM9H9U7yvvPzauyuNbxDtqlF4l3HifbRrjEuINWomuQ
          repository_url: https://test.pypi.org/legacy/
